### ISSUE TITLE
UTF8 in file names not supported

### ISSUE THREAD

**Issue by RoelWKramer** [ahankinson/pybagit#4]
When i try to bag a set of files with unicode chars in it, pybagit fails.

I expected pybagit to include those filenames in the resulting bag.

Additionally I expect pybagit to crash on this error, but somehow this stacktrace is printed without crashing the app. I think it has to do with pybagit.py calling multichecksum.py with subprocess.popen.

When i try it without unicode filenames, no problems occur.

Example filenames:
/dir/Kopiâren.htm
/dir/tëst.gif

The stacktrace:
Traceback (most recent call last):
  File "/srv/tu3/venv/lib/python2.7/site-packages/pybagit/multichecksum.py", line 111, in <module>
    write_manifest(args[0], ENCODING)
  File "/srv/tu3/venv/lib/python2.7/site-packages/pybagit/multichecksum.py", line 54, in write_manifest
    mfile.write("{0} {1}\n".format(csum, fl))
  File "/srv/tu3/venv/lib/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/srv/tu3/venv/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 59: ordinal not in range(128)

**Comment by WoLpH** [comment]
I can confirm that this issue has been resolved. @RoelWKramer is actually an (ex-)colleague of mine so I know it works for the current codebase now :)

**Comment by ahankinson** [comment]
Ok, great. Thanks!
